import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { Roboto, Noto_Sans} from 'next/font/google'

const noto = Noto_Sans({
  subsets: ['latin'],
  display: 'swap'
})

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // Choose the weights you need
  display: 'swap',
  variable: '--font-roboto', // Optional, useful with Tailwind
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const inter = Inter({ subsets: ['latin'], display: 'swap' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={noto.className}
      >
        {children}
      </body>
    </html>
  );
}
